import { Product } from "@/types/product";
// =======men======
export const PRODUCTS_DATA:Product[]=[
   {id:"1",
    name:"men's cloth",
        category:"men",
subcategory:"clothing",
image:"/products/men/clothe-men.webp",
price:250, 
brand:"nike", 
color:"black",
size:[38 , 39 , 40]
    },


{
id:"2",
name:"men's shoes",
category:"men",
subcategory:"shoes",
image:"/products/men/shoes-men.webp",
price:2500, 
brand:"fila",
size:[38 , 39 , 40],
color:"white",

},


{id:"3",
    name:"men's cloth",
    category:"men",
subcategory:"clothing",
image:"/products/men/clothe-men.webp",

price:25000, 
color:"white",
brand:"new blance",
size:[38 , 39 ],
isNew:true,
},

{id:"4",
name:"men's shoes",
category:"men",
subcategory:"shoes",
image:"/products/men/shoes-men.webp",

price:25000, 
brand:"puma",
size:[36 , 38 ],
color:"black"
},
  {id:"5",
    name:"womwn's cloth",
        category:"women",
        subcategory:"clothing",
        image:"/products/women/clothes-women.webp",
        brand:"nike",
        size:[38 , 39 , 40],
price:35000, 
color:"gray"

    },

{
    id:"6",
    name:"womwn's cloth",
    category:"women",
    subcategory:"clothing",
    image:"/products/women/clothes-women.webp",
    brand:"adidas",
    size:[38 , 39 , 40],
    color:"black",
    price:35000, 
    isNew:true,
},

{  id:"6",
    name:"womwn's shoes",
    category:"women",
    subcategory:"shoes",
    image:"/products/women/shoes-women.webp",
    brand:"fila",
size:[38 , 39 , 40],
color:"white",
    price:35000, 

},

{ id:"7",
    name:"womwn's shoes",
    category:"women",
    subcategory:"shoes",
    image:"/products/women/shoes-women.webp",
    brand:"reebok",
    size:[38 , 39 , 40],
    price:35000,
color:"gray",
},
{ id:"8",
    name:"gilr's cloth",
        category:"kids",
        subcategory:"girl",
        image:"/products/kids/girl-cloth.webp",
   
        price:35000,
        brand:"nike",
size:[30,31,32],
color:"pink",
    },
    {id:"9",
        name:"boy's shoes",
        category:"kids",
    subcategory:"boy",
    
            image:"/products/kids/boy-shoes.jpg",
       color:"black blue",
            brand:"fila",
            size:[27,28,29],
            price:35000,
            isNew:true,
    },
    {id:"10",
        name:"boy's cloth",
        category:"kids",
    subcategory:"boy",
            image:"/products/kids/boy-cloth.webp",
          color:"blue",
            price:35000,
            brand:"fila",
            size:[30,31,32]
    
    },
    {id:"11",
        name:"girl's shoes",
        category:"kids",
        subcategory:"girl",
        image:"/products/kids/shoes-girl.webp",
        price:35000,
    color:"white",
        brand:"new blance",
    size:[30,31,32,33],
    },
    {id:"12",
        name:"soccer ball",
            category:"sports",
            subcategory:"soccer",
            image:"/products/sports/soccer-1.webp",
        size:[],
            price:35000,
            brand:"nike",
    color:"white and black"
    
        },
        {id:"13",
            name:"tennis ball",
            category:"sports",
            subcategory:"tennis",
            image:"/products/sports/tennis.webp",
           color:"yellow",
                price:35000,
                size:[],
        brand:"adidas",
        isNew:true,
        },
    
]


