import type { Metadata } from "next";

import "./globals.css";

import { Suspense } from "react";
import { Loader2 } from "lucide-react";
import Footer from "@/components/layout/main/Footer";
import { Toaster } from "react-hot-toast";
import HeaderWrapper from "@/components/layout/main/HeaderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <Suspense fallback={<Loader2 />}>
          <HeaderWrapper />
          {children}
          <Footer />
          <Toaster
            position="top-center"
            toastOptions={{
              className:
                "bg-background text-foreground border rounded-xl text-sm font-medium",
              duration: 4000,
            }}
          />
        </Suspense>
      </body>
    </html>
  );
}
