import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/layout/main/Header";
import { Suspense } from "react";
import { Loader2 } from "lucide-react";
import Footer from "@/components/layout/main/Footer";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans", geist.variable)}>
      <Suspense fallback={<Loader2 />}>
        <body className="min-h-full flex flex-col">
          <Header />
          {children}
          <Footer/>
        </body>
      </Suspense>
    </html>
  );
}
